### ISSUE TITLE
new issue today -- Uncaught TypeError: Fancy.$.ajdecimalSeparatorax is not a function

### ISSUE THREAD

**Issue by brett005** [FancyGrid/FancyGrid#168]
hi today i have got this error from fancygrid it was working good and i have touch nothing on my code 
did any one have any idea please ?

It's same error i saw in fancygrid gallery demo on fancygrid website

https://fancygrid.com/tutorials-samples/server/data-db/
![Sans titre](https://user-images.githubusercontent.com/42254958/205631189-1cd25f52-347c-49f9-9cdd-2191a44eaa70.jpg)

Uncaught TypeError: Fancy.$.ajdecimalSeparatorax is not a function
    at Fancy.Ajax (fancy.min.js:9:55462)
    at constructor.loadData (server-data.min.js?_v=17175:1:2009)
    at constructor.initProxy (server-data.min.js?_v=17175:1:980)
    at new constructor (fancy.min.js:9:37728)
    at constructor.initStore (grid.min.js?_v=17175:1:27512)
    at constructor.init (fancy.min.js:9:156885)
    at i (fancy.min.js:9:159570)
    at constructor.<anonymous> (fancy.min.js:9:16143)
    at constructor.fire (fancy.min.js:9:32312)
    at Fancy.MODULELOAD.Fancy.MODULESLOAD.a.<computed>.e.onload (fancy.min.js:9:16230)

**Comment by brett005** [comment]
i have found the solution is with back to [v1.7.150](https://github.com/FancyGrid/FancyGrid/releases/tag/v1.7.150)

**Comment by MikeTatsky** [comment]
@brett005 
Thanks for report.
Will try to fix.

**Comment by MikeTatsky** [comment]
It was fixed.
Sorry for such critical bug.

**Comment by brett005** [comment]
Thank u
